### ISSUE TITLE
Cannot reauthenticate after token expired

### ISSUE THREAD

**Issue by gadgetchnnel** [RenierM26/ha-ezviz#110]
I am running version 0.0.9.4 of this integration) I noticed that all entities had become unavailable.
Checking in Devices & Services > Integrations I saw this:

![image](https://user-images.githubusercontent.com/2099542/162313975-7401ffd0-c2e2-4a73-8045-68981bcccf8b.png)

This also appears in the logs:

```text
2022-04-07 21:29:10 WARNING (MainThread) [homeassistant.config_entries] Config entry '********@**************' for ezviz_cloud integration could not authenticate: Token expired, Login with username and password required: {"meta":{"code":403,"message":"用户无权限操作","moreInfo":null}}
  File "/config/custom_components/ezviz_cloud/config_flow.py", line 319, in async_step_reauth
```

There are no options as far as I can tell to actually relogin apart from deleting and re-adding the integration - configure only shows this:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/2099542/162315745-9dc1f6b8-59b2-425e-938f-ee3e10a6b1e1.png">

and the only options in the menu are Rename, System Options, Documentation, DIsable, and Delete.

Should it re-login if the token expires and, if not, is there a way to login again without needing to delete and re-add the interation and potentially having to rename devices and entities.

Follow a restart of Home Assistant, I'm seeing additional messages in the log:

```text
2022-04-08 13:31:31 WARNING (MainThread) [homeassistant.config_entries] Config entry '********@***********' for ezviz_cloud integration could not authenticate: Token expired, Login with username and password required: {"meta":{"code":403,"message":"用户无权限操作","moreInfo":null}}
2022-04-08 13:31:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ezviz_cloud/config_flow.py", line 319, in async_step_reauth
    self.context["title_placeholders"] = {ATTR_SERIAL: user_input[CONF_USERNAME]}
KeyError: 'username'
```

**Comment by 1800Zeta** [comment]
I am also seeing this issue, token expired, unable to re-authenticate

**Comment by snoopfab** [comment]
Same exception message here. Restarting and reloading the integration does not work either

**Comment by 1800Zeta** [comment]
Hi @RenierM26 is there anything any of us can do to help resolve the issue of the token not renewing? Thanks

**Comment by 1800Zeta** [comment]
I just removed my account from the devices page and re-added it, all seems OK Afterwards. Not sure if I will have to do it again in a month or whatever

**Comment by RenierM26** [comment]
HI @1800Zeta,

Sorry for the wait. Should now be fixed in the latest release.

**Comment by mindtripper** [comment]
I got the same.
Solved it by deleting the integration (which I noticed was a beta version) and re-installed the latest version. Problem solved.

**Comment by alexreddy78** [comment]
@RenierM26 Dear Developer

It is still an issue with re-authenticate.. removed integration, reinstall, but no results..

BRGDS

**Comment by alexreddy78** [comment]
Update: after 2 hours and re-install all back to normal. Probably something was wrong with account or main server of Ezviz
